### ISSUE TITLE
hide header video animation not working

### ISSUE THREAD

**Issue by lKarmaKat** [sarequl/Netflix-Helper#19]
**Is your feature request related to a problem? Please describe.**
The hide header video animation feature doesn't work anymore

**Describe the solution you'd like**
Change the query selector from span to div

**Additional context**
I did the change and tested it, it works.
I don't know how to make a pull request :(

**Comment by sarequl** [comment]
Hi @LloydWes 

Thank you for bringing up the issue. I will make the necessary changes and push the updated version to the Chrome Web Store as soon as possible.
